### ISSUE TITLE
System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument 'false'.

### ISSUE THREAD

**Issue by gnaneswarreddy** [Dynatrace/Dynatrace-AppMon-TFS-Integration-Plugin#4]
Getting the ParameterBindingException if Activate dotnet agent is not selected, If selected same message is getting displayed with true value.

**Comment by heydenb** [comment]
Which version of TFS are you using? I don't have this issue on our test environment.

**Comment by johnmbaughman** [comment]
I had a similar problem after updating the build agent server to WMF 5.1 (PowerShell 5.1).

`[bool]$activateDotNetAgentBool = Convert-String $activateDotNetAgent Boolean` 
should become 
`[bool]$activateDotNetAgentBool = [bool]::Parse($activateDotNetAgent)`

The mandatory parameter _should_ prevent this from failing, but maybe wrap with a try/catch block?

Here's where I found this after hours of searching... [https://stackoverflow.com/questions/16983810/how-to-convert-string-to-boolean-in-this-powershell-code-for-exchange-online](https://stackoverflow.com/questions/16983810/how-to-convert-string-to-boolean-in-this-powershell-code-for-exchange-online)

**Comment by Manuel-Cabrera** [comment]
Hi. The same problem using the task on VSTS 2017 Update 3 On-prem. 

Are you planning to fix it?

**Comment by heydenb** [comment]
fixed it in release 2.4.5
I would appreciate if someone could test this change, because on our environment it worked before as well.

**Comment by Manuel-Cabrera** [comment]
Ok, I've tested and it works fine in my environment.

Thanks!!
