### ISSUE TITLE
DT_SERVICE_ENDPOINT_ID not set

### ISSUE THREAD

**Issue by emiltorlen** [Dynatrace/Dynatrace-AppMon-TFS-Integration-Plugin#6]
Hi, 
I've been trying to use this plugin for AppMon v7.0 and TFS v17.2

I get the problem that the environment variable is not set in Registertestrun.

This is where it stops.

if (-not $env:DT_SERVICE_ENDPOINT_ID){
    Write-Host "##vso[task.logissue type=error;]This task can only be used in combination with the -Dynatrace Register Testrun- task which should be executed first!"
    exit 1
}

I am using the release for AppMon v7.0

**Comment by emiltorlen** [comment]
There are only changes to the set property for two variables from what I could see. In "RegisterTestrun.ps1" 

Write-Host "##vso[task.setvariable variable=VARIABLE;]$variable"

don't have the possibility to create a pull request. But you will notice.

**Comment by heydenb** [comment]
In the latest release 2.4.7, this is fixed
